name: Rust Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: check
      run: cargo check
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/synthetic-data-generator
        asset_name: synthetic-data-generator
        tag: ${{ github.ref }}
        overwrite: true
        
        

